version: '3.9'

services:

  loadbalancer:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: loadbalancer
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend1:
    image: nginx:alpine
    ports:
      - "8081:80"
    restart: always

  backend2:
    image: tomcat:9.0
    ports:
      - "8082:8080"
    restart: always

  backend3:
    image: nginx:alpine
    container_name: backend3
    ports:
      - "8083:80"
    volumes:
      - ./backend3/index.html:/usr/share/nginx/html/index.html
    restart: always
